import csv
from datetime import date
import numpy as np


today = date.today()
todayDate = today.strftime("%m/%d/%y") # mm/dd/y
Re = 6356

# Change to network center from data.
netw_center = np.array([29.760, -95.37])



title = ['# Generated by ChargePol']
header_descriptions = ['#charge (pos/neg)', 'time (UT sec)', 'bottom height of layer (km)',
                       'depth of layer (km)', 'x distance from LMA center (km)', ' y distance from LMA center (km)', 'longitude', 'latitude']
headers = ['charge', 'time', 'zmin', 'zwidth', 'x', 'y', 'lon', 'lat', 'Date']


with open("betterFormatChargePol.csv", 'w', newline='') as file1:
    writer = csv.writer(file1)
    # write the first 3 lines of titles/headers
    writer.writerow(title)
    writer.writerow(header_descriptions)
    writer.writerow(headers)

    with open("new_chargepol_20230124.csv", 'r', newline='') as file2:
        # write the lat lon and dates for each row

        reader2 = csv.reader(file2)
        rowLength = list(reader2)

        for row in rowLength:
            pos_lat = (((180*float(row[5]))/(np.pi*Re)))+netw_center[0] #row[5] is the column for y or "pos_flay"
            #print(pos_lat)

            pos_lon = ((360*float(row[4]))/(2*np.pi*Re*np.cos(np.pi*pos_lat/180)))+netw_center[1] #row[4] is the column for x or "pos_flax"
            #print(pos_lon)

            row.append(pos_lat)
            row.append(pos_lon)
            row.append(todayDate)
            writer.writerow(row)



